diff a/arch/arm/mach-omap2/Makefile b/arch/arm/mach-omap2/Makefile	(rejected hunks)
@@ -346,7 +346,6 @@ obj-$(CONFIG_ION_OMAP)			+= omap4_ion.o
 obj-$(CONFIG_ARCH_OMAP4)		+= omap_dmm.o
 obj-$(CONFIG_OMAP_FIQ_DEBUGGER)		+= omap_fiq_debugger.o
 obj-$(CONFIG_RQ_STATS)      		+= rq_stats.o 
-obj-$(CONFIG_INTELLI_PLUG) 		+= intelli_plug.o
 
 ifeq ($(CONFIG_OMAP_REBOOT_REASON),y)
 obj-$(CONFIG_ARCH_OMAP4)		+= omap4-reboot-reason.o
